version: "3.9"
services:
  web:
    build: ./backend
    # <Port exposed>: <FastAPI port running inside backend container>
    ports:
      - "8080:8080"
    depends_on: 
      - db
  db:
    build: ./database
    restart: always
    command: 
      --secure_file_priv=''
      --local_infile=1
    environment:
      MYSQL_DATABASE: 'umami_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: 'America/Los_Angeles'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes: 
      - ./database/data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/~init.sql
      - ./database/mock.sql:/docker-entrypoint-initdb.d/~mock.sql
