version: "3.9"
services:
  web:
    build: ./backend
    # <Port exposed>: <FastAPI port running inside backend container>
    ports:
      - "8080:8080"
  db:
    build: ./database
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
