# Initialize_Tables
CALL umami_db.createUsersTable;
CALL umami_db.createRecipesTable;
CALL umami_db.createIngredientsInfoTable;
CALL umami_db.createIngredientsTable;
CALL umami_db.createRecipeStepsTable;
CALL umami_db.createImagesTable;
CALL umami_db.createUserActivityTable;
CALL umami_db.createPantryTable;
