// Redux
export const GROCERY = 'GROCERY';
export const GROCERY_ADD = 'GROCERY_ADD';
export const GROCERY_REMOVE = 'GROCERY_REMOVE';
export const INGREDIENTS = 'INGREDIENTS';

// SAGA
export const GET_GROCERY = 'GET_GROCERY';
export const ADD_GROCERY_INGREDIENT = 'ADD_GROCERY_INGREDIENT';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const ADD_RECIPE_INGREDIENT = 'ADD_RECIPE_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const GET_ALL_INGREDIENTS = 'GET_ALL_INGREDIENTS';
export const SEARCH_INGREDIENTS = 'SEARCH_INGREDIENTS';
