// Redux
export const PANTRY = 'PANTRY';
export const PANTRY_ADD = 'PANTRY_ADD';
export const PANTRY_REMOVE = 'PANTRY_REMOVE';
export const INGREDIENTS = 'INGREDIENTS';

// Saga
export const GET_PANTRY = 'GET_PANTRY';
export const ADD_PANTRY_INGREDIENT = 'ADD_PANTRY_INGREDIENT';
export const REMOVE_PANTRY_INGREDIENT = 'REMOVE_PANTRY_INGREDIENT';
export const REMOVE_RECIPE_INGREDIENT = 'REMOVE_RECIPE_INGREDIENT';
export const GET_ALL_INGREDIENTS = 'GET_ALL_INGREDIENTS';
export const SEARCH_INGREDIENTS = 'SEARCH_INGREDIENTS';
