// Redux
export const LIKED_RECIPES = 'LIKED_RECIPES';
export const MY_RECIPES = 'MY_RECIPES';
export const MY_NOTIFICATIONS = 'MY_NOTIFICATIONS';

// Saga
export const GET_LIKEDRECIPES = 'GET_LIKEDRECIPES';
export const GET_MYRECIPES = 'GET_MYRECIPES';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
