// Redux
export const RECIPE = 'RECIPE';
export const REGISTER_LIKE_RECIPE = 'REGISTER_LIKE_RECIPE';
export const REGISTER_VIEW_RECIPE = 'REGISTER_VIEW_RECIPE';
export const LIKE_RECIPE = 'LIKE_RECIPE';

// Saga
export const POST_RECIPE = 'POST_RECIPE';
export const GET_RECIPE = 'GET_RECIPE';
export const POST_RECIPE_LIKE = 'POST_RECIPE_LIKE';
export const GET_RECIPE_LIKE = 'GET_RECIPE_LIKE';
export const POST_RECIPE_VIEW = 'POST_RECIPE_VIEW';
export const POST_RECIPE_URL = 'POST_RECIPE_URL';
