// Redux
export const RECIPE = 'RECIPE';
export const VIDEO_RECIPE = 'VIDEO_RECIPE';
export const REGISTER_LIKE_RECIPE = 'REGISTER_LIKE_RECIPE';
export const REGISTER_VIEW_RECIPE = 'REGISTER_VIEW_RECIPE';
export const LIKE_RECIPE = 'LIKE_RECIPE';
export const RECIPE_STEP = 'RECIPE_STEP';
export const REMOVE_RECIPE_STEP = 'REMOVE_RECIPE_STEP';
export const REPLACE_RECIPE_STEP = 'REPLACE_RECIPE_STEP';
export const WEB_RECIPE = 'WEB_RECIPE';

// Saga
export const POST_RECIPE = 'POST_RECIPE';
export const GET_RECIPE = 'GET_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const PUT_RECIPE = 'PUT_RECIPE';
export const POST_RECIPE_LIKE = 'POST_RECIPE_LIKE';
export const GET_RECIPE_LIKE = 'GET_RECIPE_LIKE';
export const POST_RECIPE_VIEW = 'POST_RECIPE_VIEW';
export const POST_RECIPE_URL = 'POST_RECIPE_URL';
export const POST_VIDEO_URL = 'POST_VIDEO_URL';
